CREATE USER "CTN_USER" PROFILE "DEFAULT"
    IDENTIFIED BY "city"
    DEFAULT TABLESPACE "CTN_DATA"
    TEMPORARY TABLESPACE "CTN_TEMP_DATA"
    QUOTA UNLIMITED ON "CTN_DATA"
    ACCOUNT UNLOCK;

GRANT connect TO "CTN_USER" WITH ADMIN OPTION; --// create session
GRANT resource to "CTN_USER" with admin option;
