CREATE SMALLFILE TABLESPACE "CTN_DATA"
    DATAFILE '/opt/oracle/oradata/XE/XEPDB1/ctn_data.dbf' SIZE 5M
    AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED
    LOGGING
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TEMPORARY TABLESPACE "CTN_TEMP_DATA"
    TEMPFILE '/opt/oracle/oradata/XE/XEPDB1/ctn_temp_data.dbf' SIZE 5M
    AUTOEXTEND ON NEXT 2M MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;