SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, DEPARTMENT_NAME, C.COUNTRY_NAME FROM (DEPARTMENTS)
LEFT JOIN TEST.EMPLOYEES E on DEPARTMENTS.DEPARTMENT_ID = E.DEPARTMENT_ID
LEFT JOIN TEST.LOCATIONS L on DEPARTMENTS.LOCATION_ID = L.LOCATION_ID
LEFT JOIN TEST.COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
LEFT JOIN TEST.REGIONS R on C.REGION_ID = R.REGION_ID
WHERE CITY = 'Oxford'