SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE ,E.SALARY, DEPARTMENT_NAME, C.COUNTRY_NAME
FROM (DEPARTMENTS)
         LEFT JOIN TEST.EMPLOYEES E on DEPARTMENTS.DEPARTMENT_ID = E.DEPARTMENT_ID
        LEFT JOIN TEST.JOBS J on J.JOB_ID = E.JOB_ID
         LEFT JOIN TEST.LOCATIONS L on DEPARTMENTS.LOCATION_ID = L.LOCATION_ID
         LEFT JOIN TEST.COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
WHERE EMPLOYEE_ID BETWEEN 100 AND 110
ORDER BY SALARY DESC