SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY, r.REGION_NAME
FROM EMPLOYEES e
         FULL OUTER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
         FULL OUTER JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
         FULL OUTER JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
         FULL OUTER JOIN REGIONS r ON c.REGION_ID = r.REGION_ID
WHERE r.REGION_NAME = 'Europe' AND e.SALARY < 9000 AND e.SALARY <= 17000;