SELECT DISTINCT d.DEPARTMENT_NAME, d.DEPARTMENT_ID
FROM DEPARTMENTS d
         FULL OUTER JOIN EMPLOYEES e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
         FULL OUTER JOIN  JOBS j ON e.JOB_ID = j.JOB_ID
WHERE j.MAX_SALARY > 15000;