SELECT e.FIRST_NAME, e.LAST_NAME, j.JOB_TITLE, c.COUNTRY_NAME
FROM EMPLOYEES e
         FULL OUTER JOIN JOBS j ON e.JOB_ID = j.JOB_ID
         FULL OUTER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
         FULL OUTER JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
         FULL OUTER JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID;