CREATE TABLE Category
(
    id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE Product
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name        VARCHAR2(255) NOT NULL,
    price       NUMBER(10, 2) NOT NULL,
    category_id NUMBER,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT fk_category FOREIGN KEY (category_id)
        REFERENCES Category (id)
            ON DELETE CASCADE
);