CREATE TABLE Recipe
(
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    description  CLOB,
    cooking_time NUMBER(10, 2),
    servings     NUMBER(2)
);

CREATE TABLE CategoryIngredient
(
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100)
);

CREATE TABLE Ingredient
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    category_id NUMBER,
    CONSTRAINT fk_category_ingredient FOREIGN KEY (category_id) REFERENCES CategoryIngredient (id)
);

CREATE TABLE RecipeIngredient
(
    recipe_id     NUMBER,
    ingredient_id NUMBER,
    quantity      VARCHAR2(20),
    PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT fk_recipe FOREIGN KEY (recipe_id) REFERENCES Recipe (id),
    CONSTRAINT fk_ingredient FOREIGN KEY (ingredient_id) REFERENCES Ingredient (id)
);