CREATE USER "MKR_USER" PROFILE "DEFAULT"
    IDENTIFIED BY "mkr"
    DEFAULT TABLESPACE "MKR_DATA"
    TEMPORARY TABLESPACE "MKR_TEMP_DATA"
    QUOTA UNLIMITED ON "MKR_DATA"
    ACCOUNT UNLOCK;

GRANT connect TO "MKR_USER" WITH ADMIN OPTION; --// create session
GRANT resource to "MKR_USER" with admin option;
